name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    permissions:
      contents: read

  publish_package:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 12
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish --no-git-checks --provenance
